const authoringPlan = require("../scripts/report_question_activity_authoring_plan.js");
const { spawnSync } = require("child_process");

describe("question activity authoring plan", () => {
  it("builds a deterministic next batch from real activity gaps", () => {
    const first = authoringPlan.buildPlan({ batchSize: 12 });
    const second = authoringPlan.buildPlan({ batchSize: 12 });

    expect(second).toEqual(first);
    expect(first.reportVersion).toBe("question-activity-authoring-plan-v1");
    expect(first.policy).toMatchObject({
      deterministic: true,
      noFakeData: true,
      noAutoGeneratedQuestions: true,
    });
    // 2026-05-04: all activity gaps closed. ready = true. If a future regression
    // introduces gaps, ready will become false and this assertion will catch it.
    expect(first.summary.totalGaps).toBe(0);
    expect(first.summary.nextBatchSize).toBe(0);
    expect(first.summary.svcollegePriorityGaps).toBe(0);
    expect(first.summary.ready).toBe(true);
  });

  it("renders markdown without creating activity content", () => {
    const plan = authoringPlan.buildPlan({ batchSize: 3 });
    const markdown = authoringPlan.toMarkdown(plan);

    expect(markdown).toContain("# Question Activity Authoring Plan");
    expect(markdown).not.toContain("generated question");
  });

  it("strict mode passes when there are no real activity gaps remaining", () => {
    const result = spawnSync(
      process.execPath,
      ["scripts/report_question_activity_authoring_plan.js", "--strict", "--summary"],
      { encoding: "utf8" },
    );

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('"ready": true');
  });
});
