const authoringPlan = require("../scripts/report_question_activity_authoring_plan.js");

describe("question activity authoring plan", () => {
  it("builds a deterministic next batch from real activity gaps", () => {
    const first = authoringPlan.buildPlan({ batchSize: 12 });
    const second = authoringPlan.buildPlan({ batchSize: 12 });

    expect(second).toEqual(first);
    expect(first.reportVersion).toBe("question-activity-authoring-plan-v1");
    expect(first.policy).toMatchObject({
      deterministic: true,
      noFakeData: true,
      noAutoGeneratedQuestions: true,
    });
    expect(first.summary.totalGaps).toBe(231);
    expect(first.summary.nextBatchSize).toBe(12);
    expect(first.summary.ready).toBe(false);
  });

  it("prioritizes SVCollege lesson gaps before non-priority legacy gaps", () => {
    const plan = authoringPlan.buildPlan({ batchSize: 8 });

    expect(plan.nextBatch).toHaveLength(8);
    expect(plan.nextBatch[0]).toMatchObject({
      lessonId: "lesson_design_systems",
      nextActivity: "trace",
    });
    plan.nextBatch.forEach((item) => {
      expect(item.key).toContain("::");
      expect(item.requiredEvidence).toContain("real conceptKey");
      expect(["trace", "bug", "build", "review"]).toContain(item.nextActivity);
    });
    expect(plan.nextBatch.some((item) => item.lessonId === "ai_development")).toBe(false);
  });

  it("renders markdown without creating activity content", () => {
    const plan = authoringPlan.buildPlan({ batchSize: 3 });
    const markdown = authoringPlan.toMarkdown(plan);

    expect(markdown).toContain("# Question Activity Authoring Plan");
    expect(markdown).toContain("Each item below still requires manual authoring/review");
    expect(markdown).not.toContain("generated question");
  });
});
