const authoringPlan = require("../scripts/report_question_activity_authoring_plan.js");
const { spawnSync } = require("child_process");

describe("question activity authoring plan", () => {
  it("builds a deterministic next batch from real activity gaps", () => {
    const first = authoringPlan.buildPlan({ batchSize: 12 });
    const second = authoringPlan.buildPlan({ batchSize: 12 });

    expect(second).toEqual(first);
    expect(first.reportVersion).toBe("question-activity-authoring-plan-v1");
    expect(first.policy).toMatchObject({
      deterministic: true,
      noFakeData: true,
      noAutoGeneratedQuestions: true,
    });
    expect(first.summary.totalGaps).toBeGreaterThanOrEqual(150);
    expect(first.summary.nextBatchSize).toBe(12);
    expect(first.summary.svcollegePriorityGaps).toBe(0);
    expect(first.summary.ready).toBe(false);
  });

  it("keeps SVCollege-priority activity gaps closed before deferred gaps", () => {
    const plan = authoringPlan.buildPlan({ batchSize: 8 });

    expect(plan.nextBatch).toHaveLength(8);
    expect(plan.summary.svcollegePriorityGaps).toBe(0);
    expect(plan.nextBatch[0]).toMatchObject({
      lessonId: "ai_development",
      nextActivity: "trace",
    });
    plan.nextBatch.forEach((item) => {
      expect(item.key).toContain("::");
      expect(item.requiredEvidence).toContain("real conceptKey");
      expect(["trace", "bug", "build", "review"]).toContain(item.nextActivity);
    });
    expect(plan.nextBatch.some((item) => item.lessonId === "lesson_design_systems")).toBe(false);
  });

  it("renders markdown without creating activity content", () => {
    const plan = authoringPlan.buildPlan({ batchSize: 3 });
    const markdown = authoringPlan.toMarkdown(plan);

    expect(markdown).toContain("# Question Activity Authoring Plan");
    expect(markdown).toContain("Each item below still requires manual authoring/review");
    expect(markdown).not.toContain("generated question");
  });

  it("fails strict mode while real activity gaps remain", () => {
    const result = spawnSync(
      process.execPath,
      ["scripts/report_question_activity_authoring_plan.js", "--strict", "--summary"],
      { encoding: "utf8" },
    );

    expect(result.status).toBe(1);
    expect(result.stdout).toContain('"ready": false');
    expect(result.stderr).toContain("real activity gap");
  });
});
