#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const coverage = require("./report_question_activity_coverage.js");

const ROOT = path.resolve(__dirname, "..");
const JSON_PATH = path.join(ROOT, "QUESTION_ACTIVITY_AUTHORING_PLAN.json");
const MD_PATH = path.join(ROOT, "QUESTION_ACTIVITY_AUTHORING_PLAN.md");
const REPORT_DATE = "2026-04-30";

const SVCollegeLessonPriority = Object.freeze([
  "lesson_11",
  "lesson_12",
  "lesson_13",
  "lesson_html_css_foundations",
  "lesson_tooling_git",
  "lesson_15",
  "lesson_16",
  "lesson_17",
  "lesson18",
  "lesson19",
  "lesson20",
  "lesson_sql_orm",
  "lesson_auth_security",
  "lesson_nextjs",
  "lesson_nestjs",
  "lesson_devops_deploy",
  "lesson_ai_engineering",
  "lesson_design_systems",
]);

function lessonPriority(lessonId) {
  const index = SVCollegeLessonPriority.indexOf(lessonId);
  return index === -1 ? 999 : index;
}

function activityRecommendation(row) {
  if (row.trace === 0) return "trace";
  if (row.bug === 0) return "bug";
  if (row.build === 0) return "build";
  return "review";
}

function requiredEvidence(row) {
  const next = activityRecommendation(row);
  if (next === "trace") return "Add one trace item tied to this real conceptKey and code-bearing behavior.";
  if (next === "bug") return "Add one bug-hunt item tied to this real conceptKey and a real mistake pattern.";
  if (next === "build") return "Add one mini-build item tied to this real conceptKey and a real expected behavior.";
  return "Review existing activity item quality before marking complete.";
}

function buildPlan({ batchSize = 40 } = {}) {
  const coverageReport = coverage.buildReport();
  const rows = coverage.buildRows()
    .filter((row) => row.relevant && !row.ready)
    .map((row) => ({
      ...row,
      lessonPriority: lessonPriority(row.lessonId),
      nextActivity: activityRecommendation(row),
      requiredEvidence: requiredEvidence(row),
    }))
    .sort((a, b) =>
      a.lessonPriority - b.lessonPriority ||
      a.lessonId.localeCompare(b.lessonId) ||
      a.conceptName.localeCompare(b.conceptName, "he"),
    );
  const size = Math.max(1, Number(batchSize) || 40);
  const nextBatch = rows.slice(0, size).map((row, index) => ({
    order: index + 1,
    key: row.key,
    lessonId: row.lessonId,
    lessonTitle: row.lessonTitle,
    conceptName: row.conceptName,
    trace: row.trace,
    build: row.build,
    bug: row.bug,
    nextActivity: row.nextActivity,
    requiredEvidence: row.requiredEvidence,
  }));

  return {
    reportVersion: "question-activity-authoring-plan-v1",
    date: REPORT_DATE,
    policy: {
      deterministic: true,
      noFakeData: true,
      noAutoGeneratedQuestions: true,
      rule: "This plan only orders real coverage gaps. It does not create, backfill, or promote activity content.",
    },
    sourceCoverage: coverageReport.summary,
    summary: {
      totalGaps: rows.length,
      nextBatchSize: nextBatch.length,
      svcollegePriorityGaps: rows.filter((row) => row.lessonPriority < 999).length,
      deferredNonPriorityGaps: rows.filter((row) => row.lessonPriority >= 999).length,
      ready: coverageReport.summary.ready,
    },
    nextBatch,
  };
}

function toMarkdown(plan) {
  return [
    "# Question Activity Authoring Plan",
    "",
    `Date: ${plan.date}`,
    "",
    "## Summary",
    "",
    `- Coverage ready: ${plan.summary.ready ? "yes" : "no"}`,
    `- Total activity gaps: ${plan.summary.totalGaps}`,
    `- Next authoring batch: ${plan.summary.nextBatchSize}`,
    `- SVCollege-priority gaps: ${plan.summary.svcollegePriorityGaps}`,
    `- Deferred non-priority gaps: ${plan.summary.deferredNonPriorityGaps}`,
    "",
    "## Policy",
    "",
    `- ${plan.policy.rule}`,
    "- Each item below still requires manual authoring/review before P6.3.1 can close.",
    "",
    "## Next Batch",
    "",
    plan.nextBatch.length
      ? "| # | Concept | Lesson | Next activity | Current activity | Evidence required |"
      : "- No gaps.",
    plan.nextBatch.length ? "|---:|---|---|---|---|---|" : "",
    ...plan.nextBatch.map((item) =>
      `| ${item.order} | \`${item.key}\` | ${item.lessonTitle} | ${item.nextActivity} | Trace ${item.trace} · Build ${item.build} · Bug ${item.bug} | ${item.requiredEvidence} |`,
    ),
  ].filter(Boolean).join("\n");
}

function run(argv = process.argv.slice(2)) {
  const batchArg = argv.find((arg) => arg.startsWith("--batch="));
  const batchSize = batchArg ? Number(batchArg.split("=")[1]) : 40;
  const plan = buildPlan({ batchSize });
  if (argv.includes("--write")) {
    fs.writeFileSync(JSON_PATH, `${JSON.stringify(plan, null, 2)}\n`);
    fs.writeFileSync(MD_PATH, `${toMarkdown(plan)}\n`);
  }
  if (argv.includes("--summary")) {
    process.stdout.write(`${JSON.stringify(plan.summary, null, 2)}\n`);
  } else {
    process.stdout.write(`${toMarkdown(plan)}\n`);
  }
  if (argv.includes("--strict")) {
    const valid = plan.policy.noFakeData === true &&
      plan.policy.noAutoGeneratedQuestions === true &&
      plan.nextBatch.every((item) => item.key && item.nextActivity && item.requiredEvidence);
    if (!valid) process.exitCode = 1;
  }
  return plan;
}

if (require.main === module) run();

module.exports = {
  SVCollegeLessonPriority,
  buildPlan,
  run,
  toMarkdown,
};
